backend:
  name: github
  repo: jenniferlloyd/netlifyplay
  publish_mode: editorial_workflow
  branch: master

media_folder: "media/uploads"

collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "TEDDY FAIL"
        name: "TEDDYfail"
        file: "_data/TEDDYfail.yml"
        fields: 
          - { label: 'Title', name: 'title', widget: 'string'}
          - { label: 'Content', name: 'content', widget: 'markdown' }
      - label: "Home page"
        name: "home"
        file: "_data/home.yml"
        fields: 
          - label: "Banner"
            name: "banner"
            widget: "object"
            fields: 
              - label: "Join title"
                name: "jointitle"
                widget: "string"
              - label: "Banner image"
                name: "image"
                widget: "image"
              - label: "Home About"
                name: "homeabout"
                widget: "object"
                fields: 
                  - label: "About title"
                    name: "title"
                    widget: "string"
                  - label: "About text"
                    name: "text"
                    widget: "text"
                  - label: "About_link"
                    name: "link"
                    widget: "string"
                  - label: "About_Icon"
                    name: "icon"
                    widget: "image"
              - label: "For_Physicians"
                name: "for_phys"
                widget: "object"
                fields: 
                  - label: "Physician_Title"
                    name: "title"
                    widget: "string"
                  - label: "Physician_text"
                    name: "text"
                    widget: "text"
                  - label: "Physician_link"
                    name: "link"
                    widget: "string"
                  - label: "Physician_Icon"
                    name: "icon"
                    widget: "image"